export const STATES = [
    
    { title: 'Aguascalientes', id: 'AGS', color: '#8dd3c7'},
    { title: 'Baja California', id: 'BC', color: '#ffffb3'},
    { title: 'Baja California Sur', id: 'BCS', color: '#bebada'},
    { title: 'Campeche', id: 'CAMP', color: '#fb8072'},
    { title: 'Chiapas', id: 'CHIS', color: '#80b1d3'},
    { title: 'Chihuahua', id: 'CHIH', color: '#fdb462'},
    { title: 'Ciudad de México', id: 'CDMX', color: '#b3de69'},
    { title: 'Coahuila', id: 'COAH', color: '#fccde5'},
    { title: 'Colima', id: 'COL', color: '#d9d9d9'},
    { title: 'Durango', id: 'DGO', color: '#bc80bd'},
    { title: 'Guanajuato', id: 'GTO', color: '#ccebc5'},
    { title: 'Guerrero', id: 'GRO', color: '#ffed6f'},
    { title: 'Hidalgo', id: 'HGO', color: '#8dd3c7'},
    { title: 'Jalisco', id: 'JAL', color: '#ffffb3'},
    { title: 'México', id: 'MEX', color: '#bebada'},
    { title: 'Michoacán', id: 'MICH', color: '#fb8072'},
    { title: 'Morelos', id: 'MOR', color: '#80b1d3'},
    { title: 'Nayarit', id: 'NAY', color: '#fdb462'},
    { title: 'Nuevo León', id: 'NL', color: '#b3de69'},
    { title: 'Oaxaca', id: 'OAX', color: '#fccde5'},
    { title: 'Puebla', id: 'PUE', color: '#d9d9d9'},
    { title: 'Querétaro', id: 'QRO', color: '#bc80bd'},
    { title: 'Quintana Roo', id: 'QROO', color: '#ccebc5'},
    { title: 'San Luis Potosí', id: 'SLP', color: '#8dd3c7'},
    { title: 'Sinaloa', id: 'SIN', color: '#ffed6f'},
    { title: 'Sonora', id: 'SON', color: '#ffffb3'},
    { title: 'Tabasco', id: 'TAB', color: '#bebada'},
    { title: 'Tamaulipas', id: 'TAMP', color: '#fb8072'},
    { title: 'Tlaxcala', id: 'TLAX', color: '#80b1d3'},
    { title: 'Veracruz', id: 'VER', color: '#fdb462'},
    { title: 'Yucatan', id: 'YUC', color: '#b3de69'},
    { title: 'Zacatecas', id: 'ZAC', color: '#fccde5'}
];

export const STATE_COLORS = {
    'AGS':{color: '#8dd3c7', title: 'Aguascalientes'},
    'BC':{color: '#ffffb3', title: 'Baja California'},
    'BCS':{color: '#bebada', title: 'Baja California Sur'},
    'CAMP':{color: '#fb8072', title: 'Campeche'},
    'CHIS':{color: '#80b1d3', title: 'Chiapas'},
    'CHIH':{color: '#fdb462', title: 'Chihuahua'},
    'CDMX':{color: '#b3de69', title: 'Ciudad de México'},
    'COAH':{color: '#fccde5', title: 'Coahuila'},
    'COL':{color: '#d9d9d9', title: 'Colima'},
    'DGO':{color: '#bc80bd', title: 'Durango'},
    'GTO':{color: '#ccebc5', title: 'Guanajuato'},
    'GRO':{color: '#ffed6f', title: 'Guerrero'},
    'HGO':{color: '#8dd3c7', title: 'Hidalgo'},
    'JAL':{color: '#ffffb3', title: 'Jalisco'},
    'MEX':{color: '#bebada', title: 'México'},
    'MICH':{color: '#fb8072', title: 'Michoacán'},
    'MOR':{color: '#80b1d3', title: 'Morelos'},
    'NAY':{color: '#fdb462', title: 'Nayarit'},
    'NL':{color: '#b3de69', title: 'Nuevo León'},
    'OAX':{color: '#fccde5', title: 'Oaxaca'},
    'PUE':{color: '#d9d9d9', title: 'Puebla'},
    'QRO':{color: '#bc80bd', title: 'Querétaro'},
    'QROO':{color: '#ccebc5', title: 'Quintana Roo'},
    'SLP':{color: '#ffed6f', title: 'San Luis Potosí'},
    'SIN':{color: '#8dd3c7', title: 'Sinaloa'},
    'SON':{color: '#ffffb3', title: 'Sonora'},
    'TAB':{color: '#bebada', title: 'Tabasco'},
    'TAMP':{color: '#fb8072', title: 'Tamaulipas'},
    'TLAX':{color: '#80b1d3', title: 'Tlaxcala'},
    'VER':{color: '#fdb462', title: 'Veracruz'},
    'YUC':{color: '#b3de69', title: 'Yucatan'},
    'ZAC':{color: '#fccde5', title: 'Zacatecas'},
    'NACIONAL':{color: '#000', title: 'Nacional'}
}